/**
 * Static policy seeds for trail systems.
 *
 * Keyed by systemSlug (preferred) or extSystemRef.
 * These are manually curated entries used by seed-policy-austin.ts.
 *
 * policyMethod is always "manual_seed" in this file.
 * Set policyConfidence low until an official source URL is confirmed.
 */

export type DogsAllowed = "allowed" | "prohibited" | "unknown";
export type LeashPolicy = "required" | "off_leash_allowed" | "conditional" | "unknown";
export type PolicyMethod = "manual_seed" | "scrape" | "muni_open_data" | "other";

export interface PolicySeed {
  dogsAllowed: DogsAllowed;
  leashPolicy: LeashPolicy;
  leashDetails?: string;
  policySourceUrl?: string;
  policySourceTitle?: string;
  policyConfidence: number; // 0..1
  policyMethod: PolicyMethod;
  policyNotes?: string;
}

/**
 * Slugs that should never be written to DB.
 * Add artifact / placeholder system slugs here.
 */
export const POLICY_SEED_SKIP_SLUGS: Set<string> = new Set([
  "not-assigned",
]);

/**
 * Primary lookup: keyed by systemSlug.
 * Add entries here as you verify official sources.
 */
export const POLICY_SEEDS: Record<string, PolicySeed> = {
  "brushy-creek-greenbelt-regional-trail": {
    dogsAllowed: "allowed",
    leashPolicy: "required",
    leashDetails: "Leash required at all times; leash must not exceed 6 feet in length. No designated off-leash areas exist on the trail. Rule applies across all jurisdictions (Williamson County unincorporated segments, Cedar Park, and Round Rock city-limit segments).",
    policySourceUrl: "https://www.wilcotx.gov/606/Rules-Regulations",
    policySourceTitle: "Rules & Regulations | Williamson County, TX",
    policyConfidence: 0.88,
    policyMethod: "manual_seed",
    policyNotes: "Brushy Creek Regional Trail is a multi-jurisdictional trail managed primarily by Williamson County Parks & Recreation (unincorporated segments), with sections inside Cedar Park and Round Rock city limits. All three jurisdictions require leash at all times; no designated off-leash areas exist on the trail corridor. The 6-foot leash maximum is from the official Williamson County Parks Rules & Regulations (wilcotx.gov/606/Rules-Regulations), confirmed by county Parks FAQs (wilcotx.gov/1319/Parks-FAQs): 'pets must be on a leash and under control at all times.' Cedar Park's designated off-leash area is Cedar Bark Park at Veterans Memorial Park only (not on trail). Round Rock's off-leash area is Dog Depot Dog Park only (not on trail). Confidence 0.88: leash-required rule is explicit from the primary governing authority (Williamson County); 6-foot length limit is county-documented. Slight reduction from 1.0 because trail-specific rules PDF (wilcotx.gov/DocumentCenter/View/2449) was binary-encoded and not directly readable.",
  },
  "walnut-creek-corridor-southern-walnut-creek-trail": {
    dogsAllowed: "allowed",
    leashPolicy: "conditional",
    leashDetails: "Leash required (6 feet or shorter) on the trail corridor. Off-leash permitted only within the designated DOLA inside Walnut Creek Metropolitan Park — an unfenced area covering the northern portion of the park, bounded roughly by Cedar Bend Drive, the Walnut Creek waterway, and the park fence. Dogs must be leashed south of the creek. The DOLA designation does not extend to the trail corridor.",
    policySourceUrl: "https://www.austintexas.gov/department/dog-parks-leash-areas",
    policySourceTitle: "Dog Parks: Off-Leash Areas | AustinTexas.gov",
    policyConfidence: 0.82,
    policyMethod: "manual_seed",
    policyNotes: "Walnut Creek Metropolitan Park (12138 N Lamar Blvd) is an officially recognized unfenced Dog Off-Leash Area on the City of Austin Parks & Recreation DOLA list. The off-leash zone covers the northern portion of the park north of the Walnut Creek waterway, bounded by Cedar Bend Drive and the park fence. Standard DOLA rules apply: dogs must remain within sight and sound control, owner must carry a leash, rabies vaccination required, waste removal required, dogs in heat not permitted. The Walnut Creek Regional Trail / Southern Walnut Creek Trail corridor running through or adjacent to the park is part of the Austin Urban Trails network, where leash (6 feet or shorter) is required per the Urban Trails program rules — the DOLA does not extend to the trail tread. The trail also passes through sections outside the park where only the city-wide leash ordinance applies. Confidence 0.82 because the DOLA map PDF and park kiosk PDF (both city-hosted) were not directly human-readable; boundary details are corroborated by city ordinance language and GIS-hosted park materials.",
  },
  "ann-and-roy-butler-hike-and-bike-trail": {
    dogsAllowed: "allowed",
    leashPolicy: "required",
    leashDetails: "Leash required at all times on the trail. Austin City Code requires dogs to be on a leash in public areas unless designated otherwise. No off-leash section on the trail itself; nearest off-leash areas are Auditorium Shores and Red Bud Isle.",
    policySourceUrl: "https://www.austintexas.gov/department/ann-and-roy-butler-hike-and-bike-trail-and-boardwalk-lady-bird-lake",
    policySourceTitle: "Ann and Roy Butler Hike-and-Bike Trail and Boardwalk at Lady Bird Lake | AustinTexas.gov",
    policyConfidence: 0.9,
    policyMethod: "manual_seed",
    policyNotes: "Official Austin PARD page and Trail Conservancy FAQ confirm dogs allowed, leash required. Blue-green algae health advisory for lake water contact in summer/fall. Off-leash areas (Auditorium Shores, Red Bud Isle) are separate designated locations.",
  },
  "boardwalk-trail": {
    dogsAllowed: "allowed",
    leashPolicy: "required",
    leashDetails: "Leash required at all times. Austin City Code requires dogs on leash in all public areas unless designated otherwise. Boardwalk Trail is not a designated off-leash area.",
    policySourceUrl: "https://www.austintexas.gov/department/ann-and-roy-butler-hike-and-bike-trail-and-boardwalk-lady-bird-lake",
    policySourceTitle: "Ann and Roy Butler Hike-and-Bike Trail and Boardwalk at Lady Bird Lake | AustinTexas.gov",
    policyConfidence: 0.85,
    policyMethod: "manual_seed",
    policyNotes: "Boardwalk Trail is part of the Ann and Roy Butler trail system. No boardwalk-specific dog rules exist in official sources (austintexas.gov, thetrailconservancy.org). Same city-wide leash ordinance applies; 'pets on leash' ordinance is posted on trail signage throughout the system per Trail Conservancy FAQ.",
  },
  "mueller-trail": {
    dogsAllowed: "allowed",
    leashPolicy: "required",
    leashDetails: "Leash required at all times; leash must be no more than 6 feet long. Mueller Lake Park is not a designated off-leash area (DOLA). No off-leash pilot program active at this location.",
    policySourceUrl: "https://www.austintexas.gov/department/leash-areas",
    policySourceTitle: "Dog Parks / Off-Leash Areas | City of Austin Parks and Recreation Department",
    policyConfidence: 0.9,
    policyMethod: "manual_seed",
    policyNotes: "Austin City Code requires dogs on leash in all public park areas unless designated otherwise. Mueller Lake Park does not appear on the official DOLA map (March 2023) or any PARD off-leash pilot list. A community advocacy group (Mueller Dog Park Coalition) has been seeking a pilot off-leash area in the Southeast Greenway, but none is currently designated. 6-foot leash limit from official PARD Park Rules.",
  },
  "violet-crown-trail": {
    dogsAllowed: "allowed",
    leashPolicy: "required",
    leashDetails: "Dogs must remain on-leash at all times between Mile Zero Trailhead (Zilker Park) and La Crosse Trailhead. No leash length specified by trail manager; Travis County segments apply a 6-foot maximum per county park rules.",
    policySourceUrl: "https://violetcrowntrail.com/plan-your-trip/",
    policySourceTitle: "Plan Your Trip | Violet Crown Trail (Hill Country Conservancy)",
    policyConfidence: 0.9,
    policyMethod: "manual_seed",
    policyNotes: "Hill Country Conservancy is the official managing partner; AustinTexas.gov explicitly names them and directs visitors to violetcrowntrail.com for trail rules. Official rule: 'Dogs are allowed on the Violet Crown Trail between the Mile Zero Trailhead and the La Crosse Trailhead, but must remain on-leash at all times.' Trail is not a DOLA and is not part of any PARD off-leash pilot program. Dog waste bags must be packed out entirely.",
  },
  "shoal-creek-trail": {
    dogsAllowed: "allowed",
    leashPolicy: "conditional",
    leashDetails: "Leash required (6 feet or shorter) on the trail corridor at all times per Austin Urban Trails program rules. Off-leash permitted only within the designated DOLA at Shoal Creek Greenbelt (2600 N. Lamar Blvd.), a specific park area adjacent to the trail — not the full trail corridor.",
    policySourceUrl: "https://www.austintexas.gov/urbantrails",
    policySourceTitle: "Urban Trails | City of Austin",
    policyConfidence: 0.9,
    policyMethod: "manual_seed",
    policyNotes: "Urban Trails program rule applies to the full Shoal Creek Trail corridor: 'Keep pets close to you and on leashes (leash must be 6 feet or shorter).' Separately, Shoal Creek Greenbelt (2600 N. Lamar Blvd.) is a PARD-designated off-leash area (DOLA) per the official City of Austin DOLA map (March 2023). The DOLA is a bounded park area, not the 6.82-mile trail. PARD trail directory classifies the trail as 'Shared Use (Hike and Bike)' with no off-leash designation.",
  },
  "colorado-river-trail": {
    dogsAllowed: "allowed",
    leashPolicy: "required",
    leashDetails: "Leash required at all times; leash must be 6 feet or shorter per Austin Urban Trails program rules. Colorado River Trail is not a designated off-leash area (DOLA). No off-leash zones exist along the trail corridor.",
    policySourceUrl: "https://www.austintexas.gov/urbantrails",
    policySourceTitle: "Urban Trails | City of Austin",
    policyConfidence: 0.82,
    policyMethod: "manual_seed",
    policyNotes: "No dedicated city page exists under the name 'Colorado River Trail.' The trail along the Colorado River in Austin is part of the Urban Trails program, which explicitly requires pets to be 'leashed only (6 feet or shorter)' on all urban trail corridors. The City of Austin DOLA list does not include any Colorado River Trail segment as a designated off-leash area. Policy is derived from the Urban Trails program rules page and the Austin City Code Title 3 leash ordinance (§3-4-1), which mandates leashes in all public areas not specifically designated otherwise. Confidence 0.82 rather than higher because no trail-specific rules page exists for this trail name.",
  },
  "zilker-metro-loop": {
    dogsAllowed: "allowed",
    leashPolicy: "conditional",
    leashDetails: "Leash required (6 feet or shorter) on the Zilker Metro Loop trail itself — it is classified 'Shared Use (Hike and Bike)' in the city Trail Directory and is not designated off-leash. Zilker Park does contain an officially designated unfenced DOLA (one of Austin's 12 permanent off-leash areas), but that designation applies to a separate interior area of the park (the open field/Great Lawn area near 2100 Barton Springs Rd.), not the 1.99-mile perimeter loop trail. Owners must carry a leash at all times even within the DOLA.",
    policySourceUrl: "https://www.austintexas.gov/department/dog-parks-leash-areas",
    policySourceTitle: "Dog Parks: Off-Leash Areas | AustinTexas.gov",
    policyConfidence: 0.8,
    policyMethod: "manual_seed",
    policyNotes: "Zilker Park (PARK_ID 324) is confirmed as an unfenced DOLA on the City of Austin's official off-leash GIS dataset (12 total DOLAs citywide). The Zilker Metro Loop trail is listed separately in the PARD Trail Directory (2201 Barton Springs Rd., 1.99 miles, Shared Use Hike and Bike) — no off-leash designation on the trail itself. The DOLA zone is an interior open-field area of the park, not the perimeter loop. The Austin Urban Trails program requires leashes of 6 feet or shorter on all urban trail corridors. Confidence 0.8: DOLA existence is confirmed via official GIS, but the precise DOLA polygon boundary relative to the trail tread is not available in readable form (DOLA map PDFs are binary-encoded); geographic inference is based on structural distinction between perimeter loop trail and interior park open space. Note: 'Little Zilker DOLA' pilot (separate neighborhood park) ended December 2024 — unrelated to Zilker Metropolitan Park.",
  },
  "barton-corridor": {
    dogsAllowed: "allowed",
    leashPolicy: "required",
    leashDetails: "Leash required at all times; leash must be 6 feet or shorter. No designated off-leash zones exist anywhere within the greenbelt.",
    policySourceUrl: "https://www.austintexas.gov/department/barton-creek-greenbelt",
    policySourceTitle: "Barton Creek Greenbelt | City of Austin Parks and Recreation Department",
    policyConfidence: 0.95,
    policyMethod: "manual_seed",
    policyNotes: "Official PARD page states explicitly: 'Keep pets close to you and on leashes (leash must be 6 feet or shorter).' Greenbelt is not a DOLA and has no off-leash zones. PARD trail directory lists it as 'Shared Use' (no off-leash designation), unlike the two explicitly off-leash Austin trails (Emma Long Metro Park Turkey Creek Trail, Mary Moore Searight Metro Park). 'Barton Corridor' and 'Barton Creek Greenbelt' refer to the same PARD managed area. Blue-green algae caution: seasonal advisories issued for Barton Creek (notably Sculpture Falls area); dogs should not enter water when scum or film is visible.",
  },
  "red-line-trail": {
    dogsAllowed: "allowed",
    leashPolicy: "required",
    leashDetails: "Leash required at all times; leash must be 6 feet or shorter per Austin Urban Trails program rules. No designated off-leash areas exist along the trail corridor.",
    policySourceUrl: "https://www.austintexas.gov/urbantrails",
    policySourceTitle: "Urban Trails | City of Austin",
    policyConfidence: 0.85,
    policyMethod: "manual_seed",
    policyNotes: "The Red Line Trail is a multi-segment urban trail corridor running along Capital Metro's commuter rail right-of-way from downtown Austin toward Leander/Cedar Park. Currently open sections include the Boggy Creek Trail segment (Rosewood Ave to MLK Jr. Station), the ACC Highland Campus to Crestview Station segment, and a Crestview-to-US-290 segment. Managing agencies include COA Parks and Recreation, COA Transportation and Public Works, and Capital Metro. The Boggy Creek Trail section explicitly confirms dogs are welcome on leash. Standard Austin Urban Trails rules apply to all COA-managed segments. No off-leash designation exists on this corridor.",
  },
  "walnut-creek-corridor-northern-walnut-creek-trail": {
    dogsAllowed: "allowed",
    leashPolicy: "conditional",
    leashDetails: "Leash required (6 feet or shorter) on the trail corridor at all times per Austin Urban Trails program rules. Off-leash permitted only within the designated DOLA inside Walnut Creek Metropolitan Park (12138 N. Lamar Blvd.) — an unfenced area covering the northern portion of the park, north of the Walnut Creek waterway. Dogs must be leashed south of the creek and on the trail itself.",
    policySourceUrl: "https://www.austintexas.gov/department/dog-parks-leash-areas",
    policySourceTitle: "Dog Parks: Off-Leash Areas | AustinTexas.gov",
    policyConfidence: 0.80,
    policyMethod: "manual_seed",
    policyNotes: "The Northern Walnut Creek Trail (5.1 mi) is a concrete two-lane path from Balcones District Park to Walnut Creek Metropolitan Park, with 9 creek crossings. The trail terminates at Walnut Creek Metro Park. The park's DOLA boundary is described as 'from the top northern boundary of the park to the Creek' — dogs off-leash north of Walnut Creek, leashed south of it. The trail itself, winding along the creek, is on-leash under standard Austin Urban Trails rules. The DOLA is within the park grounds, distinct from the trail corridor. Same DOLA as the Southern Walnut Creek Trail (already seeded), but the northern trail enters from the west side. Confidence 0.80 because the DOLA boundary relative to the trail tread is inferred from structural distinction between trail corridor and park interior.",
  },
  "onion-creek-trail": {
    dogsAllowed: "allowed",
    leashPolicy: "conditional",
    leashDetails: "Leash required (6 feet or shorter) on the Onion Creek Trail itself per Austin Urban Trails program rules. Off-leash permitted only within the designated DOLA inside Onion Creek Metropolitan Park (7001 Onion Creek Dr.) — an unfenced 106-acre greenbelt area north of Onion Creek. The paved trail runs south of the creek and is on-leash.",
    policySourceUrl: "https://www.austintexas.gov/department/dog-parks-leash-areas",
    policySourceTitle: "Dog Parks: Off-Leash Areas | AustinTexas.gov",
    policyConfidence: 0.85,
    policyMethod: "manual_seed",
    policyNotes: "Onion Creek Metropolitan Park (517 acres total) contains an unfenced DOLA accessed from 6800 Onion Creek Drive on the north side of the creek. The DOLA boundary is Onion Creek itself: off-leash north of the creek, on-leash south. The existing 4.7-mile Onion Creek Trail urban trail runs near/through the park complex, with the main paved trail south of the creek (on-leash). The 'Dog Park Path (Onion Creek Greenbelt Trail)' is a separate trail within the park system specifically for off-leash use. Standard DOLA rules apply: dogs must remain within sight and sound control, owner must carry a leash, rabies vaccination required, waste removal required.",
  },
  "lab": {
    dogsAllowed: "allowed",
    leashPolicy: "required",
    leashDetails: "Leash required at all times; leash must be 6 feet or shorter per Austin Urban Trails program rules. The Lance Armstrong Bikeway is not a designated off-leash area.",
    policySourceUrl: "https://www.austintexas.gov/urbantrails",
    policySourceTitle: "Urban Trails | City of Austin",
    policyConfidence: 0.80,
    policyMethod: "manual_seed",
    policyNotes: "The LAB (Lance Armstrong Bikeway) is a mixed on-street and off-street bikeway running east-west across central Austin. Managed by COA Parks and Recreation and COA Transportation and Public Works. No specific trail-level dog rules differ from the standard Austin Urban Trails policy. The trail connects to the southern end of Shoal Creek Trail at W. 3rd St / Cesar Chavez, but the Shoal Creek DOLA is at the north end (~2 miles away) — not adjacent for practical purposes. No off-leash designation exists on the LAB corridor.",
  },
  "johnson-creek-trail": {
    dogsAllowed: "allowed",
    leashPolicy: "required",
    leashDetails: "Leash required at all times; leash must be 6 feet or shorter per Austin Urban Trails program rules. Johnson Creek Greenbelt is not a designated off-leash area.",
    policySourceUrl: "https://www.austintexas.gov/urbantrails",
    policySourceTitle: "Urban Trails | City of Austin",
    policyConfidence: 0.85,
    policyMethod: "manual_seed",
    policyNotes: "Johnson Creek Greenbelt Trail (2100 Veterans Dr) is a concrete hike-and-bike trail along MoPac between Veterans Drive and Enfield Road. AllTrails, BringFido, and TrailLink all confirm dogs allowed on leash. Managed by COA Parks and Recreation and COA Transportation and Public Works. Standard Austin Urban Trails rules apply. Nearest DOLA is West Austin Neighborhood Park (1317 W. 10th St), roughly 0.5–1 mile east across MoPac — not on the trail.",
  },
  "country-club-creek-trail": {
    dogsAllowed: "allowed",
    leashPolicy: "required",
    leashDetails: "Leash required at all times; leash must be 6 feet or shorter per Austin Urban Trails program rules. No designated off-leash areas exist along the trail corridor.",
    policySourceUrl: "https://www.austintexas.gov/urbantrails",
    policySourceTitle: "Urban Trails | City of Austin",
    policyConfidence: 0.75,
    policyMethod: "manual_seed",
    policyNotes: "Country Club Creek Trail connects Mable Davis Park to Roy G. Guerrero Colorado River Metro Park (400 Grove Blvd) in southeast Austin. Managed by COA Parks and Recreation and COA Transportation and Public Works. Standard Austin Urban Trails rules apply. One source mentioned an 'off-leash dog area' at Roy Guerrero Metro Park, but this does not appear on the City of Austin's official DOLA list (March 2023) — it may be an informal area or outdated information. Confidence 0.75 because of the unconfirmed Roy Guerrero off-leash claim.",
  },
  "wells-branch-trail": {
    dogsAllowed: "allowed",
    leashPolicy: "required",
    leashDetails: "Leash required at all times on the trail. City of Austin segments follow Urban Trails rules (6 feet or shorter). Wells Branch MUD segments require physical restraint at all times (no specific length stated). Two MUD off-leash areas (Willow Bend Dog Park and Big Basin Off Leash Area) are near the trail but are separate facilities — not on the trail corridor.",
    policySourceUrl: "https://wellsbranchmud.com/74-parks-a-recreation/parks/parks-rules",
    policySourceTitle: "Park Rules | Wells Branch MUD",
    policyConfidence: 0.80,
    policyMethod: "manual_seed",
    policyNotes: "Wells Branch Trail spans Austin, Austin ETJ, and Pflugerville jurisdictions. Managing agencies include both Wells Branch MUD and COA Transportation and Public Works. Wells Branch MUD park rules explicitly state: 'All dogs in the Parks must have all required vaccinations and, except for the Dog Parks, must be confined to a leash under the physical control and restraint by their owners at all times.' E-collars do not satisfy the leash rule under MUD ordinance. The MUD's two off-leash areas (Willow Bend Dog Park, Big Basin Off Leash Area) are near the trail system but are MUD-designated facilities, not City of Austin DOLAs. Austin City Code §3-4-1 applies to city-managed portions. Dual-authority outcome is the same: leash required on trail.",
  },
  "gillieland-creek-trail": {
    dogsAllowed: "allowed",
    leashPolicy: "required",
    leashDetails: "Leash required at all times per Austin City Code §3-4-1. No designated off-leash areas along the trail corridor.",
    policySourceUrl: "https://www.austintexas.gov/urbantrails",
    policySourceTitle: "Urban Trails | City of Austin",
    policyConfidence: 0.70,
    policyMethod: "manual_seed",
    policyNotes: "The 'Gillieland Creek Trail' in the Austin Urban Trails open data (jdwm-wfps) is a distinct regional trail corridor from the well-documented 'Gilleland Creek Trail' in Pflugerville. The Austin dataset shows managing agencies as 'Not Determined' and 'Other' for the Gillieland Creek Trail, with existing segments being a small portion of the larger planned regional corridor. Because specific trail management details for this corridor are sparse and the managing agency is unconfirmed, confidence is 0.70 — baseline Austin Urban Trails rules apply by default since the trail is within Austin city limits.",
  },
  "mokan-corridor-trail": {
    dogsAllowed: "allowed",
    leashPolicy: "required",
    leashDetails: "Leash required at all times; leash must be 6 feet or shorter per Austin Urban Trails program rules. No designated off-leash areas on the corridor.",
    policySourceUrl: "https://www.austintexas.gov/urbantrails",
    policySourceTitle: "Urban Trails | City of Austin",
    policyConfidence: 0.80,
    policyMethod: "manual_seed",
    policyNotes: "The MoKan Corridor Trail follows a former Missouri-Kansas-Texas Railroad right-of-way in east Austin, connecting the Pedernales St protected bike path to the Southern Walnut Creek Trail. Managed by COA Transportation and Public Works. A new trailhead near Bolm Road (opened July 2025) includes a water fountain with a dog-friendly bowl, indicating dogs are explicitly anticipated on this trail. Standard Austin Urban Trails rules apply. Full planned corridor extends to Pflugerville but existing Austin section is 1.2 miles.",
  },
  "183-tollway-shared-use-path": {
    dogsAllowed: "allowed",
    leashPolicy: "required",
    leashDetails: "Leash required at all times. CTRMA policy: 'Dogs are welcome but should remain on leash.' Austin City Code §3-4-1 also applies. No designated off-leash areas on the path.",
    policySourceUrl: "https://www.mobilityauthority.com/shared-use-paths",
    policySourceTitle: "Shared Use Paths | Central Texas Regional Mobility Authority",
    policyConfidence: 0.85,
    policyMethod: "manual_seed",
    policyNotes: "The 183 Trail runs along US 183/183 Toll from US 290 to SH 71. Operated by the Central Texas Regional Mobility Authority (CTRMA), not the City of Austin Urban Trails Program. CTRMA publishes a blanket pet policy for all shared-use paths: dogs welcome, leash required. No specific leash length stated by CTRMA, but Austin City Code §3-4-1 requires leash in all public areas. The 183 Tollway path (US 183) is distinct from the 183A path (northwest corridor toward Cedar Park/Leander).",
  },
  "ih-35-shared-use-path": {
    dogsAllowed: "allowed",
    leashPolicy: "required",
    leashDetails: "Leash required at all times; leash must be 6 feet or shorter per Austin Urban Trails program rules. No designated off-leash areas on the path.",
    policySourceUrl: "https://www.austintexas.gov/urbantrails",
    policySourceTitle: "Urban Trails | City of Austin",
    policyConfidence: 0.75,
    policyMethod: "manual_seed",
    policyNotes: "IH-35 Shared Use Path runs along the I-35 expansion project corridor. Part of Austin's urban trail network; City of Austin is the most likely managing entity for urban trail corridors along the IH-35 expansion (COA/TxDOT partnership). No trail-specific dog policy page found. Applying the Urban Trails Program's universal 6-foot leash rule is the conservative and most defensible policy. Confidence 0.75 because no CTRMA or TxDOT page explicitly names the IH-35 Shared Use Path with a dog policy.",
  },
  "us-290-manor-expressway-trail": {
    dogsAllowed: "allowed",
    leashPolicy: "required",
    leashDetails: "Leash required at all times. CTRMA policy: dogs welcome, leash required. Austin City Code §3-4-1 also applies. No designated off-leash areas on the path.",
    policySourceUrl: "https://www.mobilityauthority.com/shared-use-paths",
    policySourceTitle: "Shared Use Paths | Central Texas Regional Mobility Authority",
    policyConfidence: 0.85,
    policyMethod: "manual_seed",
    policyNotes: "The 290 Toll Shared Use Path runs parallel to the US 290 Toll (Manor Expressway) from Austin east toward Manor. Operated by CTRMA. TrailLink confirms this is a paved path, dog-friendly. Trail is heavily sun-exposed toward Manor end; no water fountains reported. The BarkTrails slug 'us-290-manor-expressway-trail' maps to what TrailLink calls the '290 Toll Shared Use Path.'",
  },
  "sh-71-shared-use-path": {
    dogsAllowed: "allowed",
    leashPolicy: "required",
    leashDetails: "Leash required at all times. CTRMA policy: dogs welcome, leash required. Austin City Code §3-4-1 also applies. No designated off-leash areas on the path.",
    policySourceUrl: "https://www.mobilityauthority.com/projects-programs/shared-use-paths/71/",
    policySourceTitle: "71 Trail | Central Texas Regional Mobility Authority",
    policyConfidence: 0.88,
    policyMethod: "manual_seed",
    policyNotes: "The 71 Trail runs along SH 71 from US 183 to SH 130, operated by CTRMA. Connects to the 183 Trail and provides access toward Austin-Bergstrom International Airport. AllTrails lists it as '71 Toll Lane Shared Use Path' — dogs on leash confirmed. CTRMA blanket pet policy applies. Austin City Code §3-4-1 also applies independently.",
  },
  "sh-45-shared-use-path": {
    dogsAllowed: "allowed",
    leashPolicy: "required",
    leashDetails: "Leash required at all times. CTRMA policy: dogs welcome, leash required. Austin City Code §3-4-1 also applies. No designated off-leash areas on the path.",
    policySourceUrl: "https://www.mobilityauthority.com/projects-programs/shared-use-paths/45sw/",
    policySourceTitle: "45SW Trail | Central Texas Regional Mobility Authority",
    policyConfidence: 0.88,
    policyMethod: "manual_seed",
    policyNotes: "The 45SW Trail runs along SH 45 SW, operated by CTRMA. AllTrails lists '45SW Shared Use Path' as dog-friendly (dogs on leash). CTRMA blanket pet policy applies. Austin City Code §3-4-1 also applies independently.",
  },
  "austin-to-manor-trail": {
    dogsAllowed: "allowed",
    leashPolicy: "required",
    leashDetails: "Leash required at all times; leash must be 6 feet or shorter per Austin Urban Trails program rules. No designated off-leash areas on the trail.",
    policySourceUrl: "https://www.austintexas.gov/urbantrails",
    policySourceTitle: "Urban Trails | City of Austin",
    policyConfidence: 0.82,
    policyMethod: "manual_seed",
    policyNotes: "Austin to Manor Trail runs from Austin toward Manor parallel to US 290. Partially overlaps with or connects to the CTRMA 290 Toll path corridor. AllTrails lists it with 81 reviews and confirms dogs on leash. The trail falls under Austin Urban Trails program rules. Austin City Code §3-4-1 also applies.",
  },
  "howard-ln-trail": {
    dogsAllowed: "allowed",
    leashPolicy: "required",
    leashDetails: "Leash required at all times per Austin City Code §3-4-1. No designated off-leash areas on the trail.",
    policySourceUrl: "https://www.austintexas.gov/urbantrails",
    policySourceTitle: "Urban Trails | City of Austin",
    policyConfidence: 0.70,
    policyMethod: "manual_seed",
    policyNotes: "Howard Lane Trail (4.9 mi) is a shared-use path along Howard Lane. Travis County's Citizens Bond Advisory Committee listed a 'Howard Lane Shared Use Path' project on the south side of Howard Lane (McNeil Drive). May be managed by City of Austin or Travis County. No trail-specific dog policy page found. Austin City Code §3-4-1 applies — leash required in all public areas. Confidence 0.70 because the trail's managing entity is unconfirmed and no AllTrails or TrailLink listing was found.",
  },
  "mopac-shared-use-path": {
    dogsAllowed: "allowed",
    leashPolicy: "required",
    leashDetails: "Leash required at all times. CTRMA policy: dogs welcome, leash required. Austin City Code §3-4-1 also applies. No designated off-leash areas on the path.",
    policySourceUrl: "https://www.mobilityauthority.com/projects-programs/shared-use-paths/mopac/",
    policySourceTitle: "MoPac Trail | Central Texas Regional Mobility Authority",
    policyConfidence: 0.88,
    policyMethod: "manual_seed",
    policyNotes: "MoPac Trail runs along Loop 1 (MoPac Expressway) from Parmer Lane to the Colorado River, operated by CTRMA. CTRMA blanket pet policy applies: dogs welcome, leash required. Austin City Code §3-4-1 also applies independently. No off-leash designation exists on this corridor.",
  },
  "mckinney-falls-parkway-trail": {
    dogsAllowed: "allowed",
    leashPolicy: "required",
    leashDetails: "Leash required at all times; leash must be no longer than 6 feet. Dogs are not allowed in the water at Upper or Lower Falls areas. Texas Parks & Wildlife Department rules apply.",
    policySourceUrl: "https://tpwd.texas.gov/state-parks/mckinney-falls",
    policySourceTitle: "McKinney Falls State Park | Texas Parks & Wildlife Department",
    policyConfidence: 0.78,
    policyMethod: "manual_seed",
    policyNotes: "McKinney Falls Parkway Trail (2.1 mi) runs along McKinney Falls Parkway within or adjacent to McKinney Falls State Park (5808 McKinney Falls Pkwy, Austin TX 78744). TPWD rules apply: leash no longer than 6 feet at all times on all trails and in the campground. Dogs are not allowed in the water (Upper and Lower Falls areas). Day-use fee of $6/adult applies. The governing authority is TPWD, not the City of Austin Urban Trails Program. Confidence 0.78 because the TPWD trails-info page does not list a specific trail named 'McKinney Falls Parkway Trail' — it may be the paved road-parallel path or a segment of the park's Onion Creek trail system.",
  },

  // ============================================================
  // Houston, TX — Policy Seeds
  // ============================================================
  // Baseline: Houston City Ordinance Chapter 6 requires leash at
  // all times on all public property. Harris County regulations
  // mirror this for unincorporated areas. Off-leash only in
  // designated fenced dog parks per Chapter 32 Sec. 32-11.
  // ============================================================

  "buffalo-bayou-greenway": {
    dogsAllowed: "allowed",
    leashPolicy: "conditional",
    leashDetails: "Leash required at all times on the trail per Houston City Ordinance Chapter 6. Off-leash permitted only inside the fenced Johnny Steele Dog Park (2929 Allen Pkwy, 2 acres, separate large/small dog areas).",
    policySourceUrl: "https://buffalobayou.org/location/buffalo-bayou-park/",
    policySourceTitle: "Buffalo Bayou Park | Buffalo Bayou Partnership",
    policyConfidence: 0.92,
    policyMethod: "manual_seed",
    policyNotes: "Buffalo Bayou Partnership rules: 'Pets must remain on leashes except in Dog Parks.' Johnny Steele Dog Park hours: 7 AM-8 PM. Max 2 dogs per person. No puppies under 4 months. No children 12 or under in dog park.",
  },
  "brays-bayou-greenway": {
    dogsAllowed: "allowed",
    leashPolicy: "conditional",
    leashDetails: "Leash required at all times on the greenway per Houston City Ordinance Chapter 6. Off-leash only inside fenced McWilliams Dog Park in Hermann Park and small fenced dog park at Mason Park, both adjacent to the greenway.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.85,
    policyMethod: "manual_seed",
    policyNotes: "The Brays Bayou Greenway passes through Hermann Park (McWilliams Dog Park, open Tue-Sun 6 AM-11 PM) and Mason Park (small fenced dog park).",
  },
  "white-oak-bayou-greenway": {
    dogsAllowed: "allowed",
    leashPolicy: "conditional",
    leashDetails: "Leash required at all times on the greenway per Houston City Ordinance Chapter 6. Off-leash only inside the fenced T.C. Jester Dog Park (4201 W T.C. Jester Blvd, 1.08 acres) adjacent to the greenway.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.88,
    policyMethod: "manual_seed",
    policyNotes: "T.C. Jester Dog Park features 31,000 sq ft large dog run and 16,000 sq ft small dog run with benches and dog drinking fountains.",
  },
  "sims-bayou-greenway": {
    dogsAllowed: "allowed",
    leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6. No designated off-leash dog parks along the Sims Bayou Greenway corridor.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.82,
    policyMethod: "manual_seed",
  },
  "greens-bayou-greenway-paved-trail": {
    dogsAllowed: "allowed",
    leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6. No designated off-leash dog parks along the Greens Bayou Greenway corridor.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.78,
    policyMethod: "manual_seed",
  },
  "greens-bayou-greenway-natural-surface-trail": {
    dogsAllowed: "allowed",
    leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6. No designated off-leash dog parks along the Greens Bayou Greenway corridor.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.78,
    policyMethod: "manual_seed",
  },
  "halls-bayou-greenway": {
    dogsAllowed: "allowed",
    leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6. No designated off-leash dog parks along the Halls Bayou Greenway corridor.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.75,
    policyMethod: "manual_seed",
  },
  "hunting-bayou-greenway": {
    dogsAllowed: "allowed",
    leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6. No designated off-leash dog parks along the Hunting Bayou Greenway corridor.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.78,
    policyMethod: "manual_seed",
  },
  "san-jacinto-bayou-greenway": {
    dogsAllowed: "allowed",
    leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.75,
    policyMethod: "manual_seed",
  },
  "memorial-park-trail": {
    dogsAllowed: "allowed",
    leashPolicy: "required",
    leashDetails: "Dogs must remain on leash at all times per Memorial Park Conservancy rules. Dogs not permitted in park water features or Hines Lake. Seymour Lieberman Trail (crushed granite) is recommended for dogs.",
    policySourceUrl: "https://www.memorialparkconservancy.org/visit/general-park-info/",
    policySourceTitle: "General Park Information | Memorial Park Conservancy",
    policyConfidence: 0.92,
    policyMethod: "manual_seed",
    policyNotes: "Memorial Park Conservancy: 'Dogs are welcome in the Park but must remain on their leash at all times.' No off-leash dog park within Memorial Park.",
  },
  "hermann-park": {
    dogsAllowed: "allowed",
    leashPolicy: "conditional",
    leashDetails: "Leash required at all times throughout the park. Off-leash only inside the fenced McWilliams Dog Park (1598 S MacGregor Way). Dogs prohibited on the train, carousel, pedal boats, Play Garden, and all buildings.",
    policySourceUrl: "https://hermannpark.org/faqs/",
    policySourceTitle: "Frequently Asked Questions | Hermann Park Conservancy",
    policyConfidence: 0.93,
    policyMethod: "manual_seed",
    policyNotes: "Hermann Park FAQ: 'Dogs are permitted in Hermann Park on a leash' and 'McWilliams Dog Park is the only area where dogs are permitted to be off leash.' McWilliams opened Oct 2023, Tue-Sun 6 AM-11 PM.",
  },
  "terry-hershey-park": {
    dogsAllowed: "allowed",
    leashPolicy: "conditional",
    leashDetails: "Leash required (6 feet or shorter) at all times on trails per Harris County Precinct 4 rules. Off-leash only inside the fenced Millie Bush Bark Park (16756 Westheimer Pkwy, 13 acres) in adjacent George Bush Park.",
    policySourceUrl: "https://cp4.harriscountytx.gov/Explore/Parks/Policies-Regulations",
    policySourceTitle: "Policies & Regulations | Harris County Precinct 4 Parks",
    policyConfidence: 0.90,
    policyMethod: "manual_seed",
    policyNotes: "HC Pct. 4: 'All dogs must be on a leash that is 6-feet long or less.' Millie Bush Bark Park is 13 acres with three small lakes and separate large/small dog sections.",
  },
  "heights-hike-bike-trail": {
    dogsAllowed: "allowed",
    leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6. No designated off-leash dog parks on the trail corridor.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.85,
    policyMethod: "manual_seed",
  },
  "spring-creek-greenway": {
    dogsAllowed: "allowed",
    leashPolicy: "required",
    leashDetails: "Leash required (6 feet or shorter) at all times per Harris County Precinct 4 rules. No designated off-leash dog parks on the greenway.",
    policySourceUrl: "https://cp4.harriscountytx.gov/Explore/Parks/Policies-Regulations",
    policySourceTitle: "Policies & Regulations | Harris County Precinct 4 Parks",
    policyConfidence: 0.88,
    policyMethod: "manual_seed",
    policyNotes: "Spring Creek Greenway is 14.5 miles managed by Harris County Precinct 4. Wildlife-sensitive corridor with gray foxes, bald eagles, and bald cypress.",
  },
  "cypress-creek-greenway": {
    dogsAllowed: "allowed",
    leashPolicy: "required",
    leashDetails: "Leash required at all times per Harris County park rules. No designated off-leash dog parks on the greenway.",
    policySourceUrl: "https://cp4.harriscountytx.gov/Explore/Parks/Policies-Regulations",
    policySourceTitle: "Policies & Regulations | Harris County Precinct 4 Parks",
    policyConfidence: 0.80,
    policyMethod: "manual_seed",
  },
  "kingwood-greenbelt-trails": {
    dogsAllowed: "allowed",
    leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6. Kingwood is within Houston city limits.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.85,
    policyMethod: "manual_seed",
    policyNotes: "Kingwood greenbelt trail system features 75+ miles of trails through 'Houston's Livable Forest.' No off-leash dog park within the greenbelt system.",
  },
  "bay-area-hike-and-bike-trail": {
    dogsAllowed: "allowed",
    leashPolicy: "required",
    leashDetails: "Leash required at all times. Dogs NOT allowed at adjacent Armand Bayou Nature Center even on leash.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.78,
    policyMethod: "manual_seed",
    policyNotes: "Trail crosses multiple jurisdictions (Houston, Pasadena, unincorporated Harris County). ABNC prohibits all pets for wildlife safety.",
  },
  "columbia-tap": {
    dogsAllowed: "allowed",
    leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6. No designated off-leash dog parks on the trail.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.85,
    policyMethod: "manual_seed",
  },
  "buffalo-bayou-park": {
    dogsAllowed: "allowed",
    leashPolicy: "conditional",
    leashDetails: "Leash required at all times on trails per Buffalo Bayou Partnership rules. Off-leash only inside the fenced Johnny Steele Dog Park (2929 Allen Pkwy).",
    policySourceUrl: "https://buffalobayou.org/location/buffalo-bayou-park/",
    policySourceTitle: "Buffalo Bayou Park | Buffalo Bayou Partnership",
    policyConfidence: 0.92,
    policyMethod: "manual_seed",
  },
  "tom-bass-regional-park": {
    dogsAllowed: "allowed",
    leashPolicy: "conditional",
    leashDetails: "Leash required at all times on park trails. Off-leash only inside the fenced Tom Bass K-9 Dog Park (3452 Fellows Rd, 10 acres, separate large/small dog areas).",
    policySourceUrl: "https://www.hcp1.net/TomBassPark",
    policySourceTitle: "Tom Bass Park | Harris County Precinct 1",
    policyConfidence: 0.88,
    policyMethod: "manual_seed",
  },
  "mason-park-trails": {
    dogsAllowed: "allowed",
    leashPolicy: "conditional",
    leashDetails: "Leash required at all times on park trails per Houston City Ordinance Chapter 6. A small fenced off-leash dog park area exists within Mason Park.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.80,
    policyMethod: "manual_seed",
  },
  "arthur-storey-park": {
    dogsAllowed: "allowed",
    leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6. No off-leash dog park at Arthur Storey Park.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.72,
    policyMethod: "manual_seed",
  },

  // ============================================================
  // Houston, TX — Baseline coverage (slug aliases + remaining trails)
  // All entries apply Houston City Ordinance Chapter 6 or Harris County
  // park rules as the baseline: leash required, dogs allowed.
  // ============================================================

  // Slug aliases — DB slug differs from the originally seeded keys above
  "bay-area-hike-bike-trail": {
    dogsAllowed: "allowed",
    leashPolicy: "required",
    leashDetails: "Leash required at all times. Dogs NOT allowed at adjacent Armand Bayou Nature Center even on leash.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.78,
    policyMethod: "manual_seed",
    policyNotes: "Trail crosses multiple jurisdictions (Houston, Pasadena, unincorporated Harris County). Armand Bayou Nature Center prohibits all pets for wildlife safety.",
  },
  "kingwood-trails": {
    dogsAllowed: "allowed",
    leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6. Kingwood is within Houston city limits.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.85,
    policyMethod: "manual_seed",
    policyNotes: "Kingwood greenbelt trail system features 75+ miles of trails. No off-leash dog park within the greenbelt system.",
  },

  // Armand Bayou corridor — city-managed H&B trail (NOT the Nature Center, which prohibits dogs)
  "armand-bayou-hike-and-bike-trail": {
    dogsAllowed: "allowed",
    leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6. The trail runs along Armand Bayou but is separate from the Armand Bayou Nature Center, which prohibits all pets.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.75,
    policyMethod: "manual_seed",
    policyNotes: "Armand Bayou Nature Center (ABNC) prohibits pets for wildlife safety. The H&B trail is managed by Houston Parks & Recreation and follows city leash ordinance.",
  },
  "armand-bayou-hike-and-bike-trail-fairmont": {
    dogsAllowed: "allowed",
    leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6. Trail segment adjacent to Armand Bayou Nature Center, which prohibits all pets.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.75,
    policyMethod: "manual_seed",
  },

  // Harris County Precinct 4 parks (higher-quality trail systems)
  "jesses-h-jones-trails": {
    dogsAllowed: "allowed",
    leashPolicy: "required",
    leashDetails: "Leash required at all times per Harris County Precinct 4 park rules. Jesse H. Jones Park is a 310-acre forest preserve with 12+ miles of hiking trails.",
    policySourceUrl: "https://cp4.harriscountytx.gov/Explore/Parks/Policies-Regulations",
    policySourceTitle: "Policies & Regulations | Harris County Precinct 4 Parks",
    policyConfidence: 0.82,
    policyMethod: "manual_seed",
  },
  "terry-hershey-park-trails": {
    dogsAllowed: "allowed",
    leashPolicy: "required",
    leashDetails: "Leash required at all times per Harris County Precinct 4 park rules. Terry Hershey Park runs 10 miles along Buffalo Bayou's west fork.",
    policySourceUrl: "https://cp4.harriscountytx.gov/Explore/Parks/Policies-Regulations",
    policySourceTitle: "Policies & Regulations | Harris County Precinct 4 Parks",
    policyConfidence: 0.82,
    policyMethod: "manual_seed",
  },
  "george-bush-park-h-b-trail": {
    dogsAllowed: "allowed",
    leashPolicy: "required",
    leashDetails: "Leash required at all times per Harris County Precinct 3 park rules. George Bush Park is a 7,800-acre regional park.",
    policySourceUrl: "https://hcp3.net/parks/george-bush-park/",
    policySourceTitle: "George Bush Park | Harris County Precinct 3",
    policyConfidence: 0.80,
    policyMethod: "manual_seed",
  },
  "spring-creek-nature-trail": {
    dogsAllowed: "allowed",
    leashPolicy: "required",
    leashDetails: "Leash required at all times per Harris County Precinct 4 park rules. Spring Creek Nature Trail runs through sensitive riparian habitat.",
    policySourceUrl: "https://cp4.harriscountytx.gov/Explore/Parks/Policies-Regulations",
    policySourceTitle: "Policies & Regulations | Harris County Precinct 4 Parks",
    policyConfidence: 0.80,
    policyMethod: "manual_seed",
  },

  // Remaining Houston/Harris County trails — standard leash-required baseline
  "river-grove-park": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "connection-to-rankin-by-others": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "mike-driscoll-park": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "woodland-hills-to-us-59": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "brays-bayou-trail": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "tony-marron-park-trails": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "lake-forest-park-trails": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "eldridge-detention-to-mcclendon-park": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "mcclendon-park": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "white-oak-bayou-trail": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "nicholson-st": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "white-oak-h-b-trail-pct-1": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Harris County Precinct 1 park rules.",
    policySourceUrl: "https://www.hcp1.net/",
    policySourceTitle: "Harris County Precinct 1 Parks",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "gears-rd-to-greens-parkway": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "sims-bayou-trail": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "newcastle-st": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "briarwick-to-keith-wiess-park": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "milby-park-to-galveston-road-sims-bayou": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "westchase-trails": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "houston-unknown-trail": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "archbishop-joseph-a-fiorenza-h-b-trail": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "lockwood-to-us-59": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "bryce-trail": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "herman-brown-park-trails": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "brock-park": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "keith-wiess-park": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "greens-bayou-trail": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "hogg-bird-sanctuary-trail": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6. Trail is within the Houston city park system along Buffalo Bayou.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "gus-wortham-park": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "centerpoint-trail": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "spring-branch-trail": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "keegans-bayou-trail": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "faulkey-gully": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "brays-bayou-connector": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "drainage-corridor": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "maxey-rd-sidewalks": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "cypresswood-equestrian-trail": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Harris County park rules. Equestrian trail — keep dogs close and under control around horses.",
    policySourceUrl: "https://cp4.harriscountytx.gov/Explore/Parks/Policies-Regulations",
    policySourceTitle: "Policies & Regulations | Harris County Precinct 4 Parks",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "turkey-creek-park-trail": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "hcfcd-54-acre-trails": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Harris County Flood Control District rules.",
    policySourceUrl: "https://www.hcfcd.org/",
    policySourceTitle: "Harris County Flood Control District",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "cypresswood-park-trails": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Harris County park rules.",
    policySourceUrl: "https://cp4.harriscountytx.gov/Explore/Parks/Policies-Regulations",
    policySourceTitle: "Policies & Regulations | Harris County Precinct 4 Parks",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "sandpiper-trails": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "collins-bike-trails": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "ymca-trails": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "cypress-creek-trail": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Harris County park rules.",
    policySourceUrl: "https://cp4.harriscountytx.gov/Explore/Parks/Policies-Regulations",
    policySourceTitle: "Policies & Regulations | Harris County Precinct 4 Parks",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "bike-barn-access-trail": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "strawberry-trail": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "emnora-trail": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "first-tee-golf-facility-road": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "hutcheson-park": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "jensen-to-mckee": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "f-m-law-park-connector-trail": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "vogel-creek-greenway": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "reddleshire-connector": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "addicks-reservoir": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times. Addicks Reservoir is managed by the US Army Corps of Engineers; Houston city ordinance applies on maintained trail areas.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "brays-oaks-trail": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "almeda-rd": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "holly-hall-st": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "harrisburg-sunset-trail": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "houston-international-promenade-trail": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "fondren-channel-trail": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "west-hc-mud-11-trails": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Harris County MUD rules and Houston City Ordinance Chapter 6.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "gessner-basin-s": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "west-hc-mud-9-trails": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Harris County MUD rules and Houston City Ordinance Chapter 6.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "jersey-village-h-b-trail": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per City of Jersey Village ordinance.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "hollister-detention-basin-trail": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "ranchstone-basin": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
  "sharpstown-trail": {
    dogsAllowed: "allowed", leashPolicy: "required",
    leashDetails: "Leash required at all times per Houston City Ordinance Chapter 6.",
    policySourceUrl: "https://www.houstontx.gov/parks/parkrules.html",
    policySourceTitle: "Park Safety and Park Rules | Houston Parks and Recreation",
    policyConfidence: 0.72, policyMethod: "manual_seed",
  },
};
