// Docs: https://www.instantdb.com/docs/modeling-data

import { i } from "@instantdb/react";

const _schema = i.schema({
  // We inferred 23 attributes!
  // Take a look at this schema, and if everything looks good,
  // run `push schema` again to enforce the types.
  entities: {
    $files: i.entity({
      path: i.string().unique().indexed(),
      url: i.string(),
    }),
    $streams: i.entity({
      abortReason: i.string().optional(),
      clientId: i.string().unique().indexed(),
      done: i.boolean().optional(),
      size: i.number().optional(),
    }),
    $users: i.entity({
      email: i.string().unique().indexed().optional(),
      imageURL: i.string().optional(),
      type: i.string().optional(),
    }),
    trailHeads: i.entity({
      accessRulesLastComputedAt: i.number().optional(),
      googleAddress: i.string().optional(),
      googleBusinessStatus: i.string().optional(),
      googleCanonicalName: i.string().optional(),
      googleLastSyncAt: i.string().optional(),
      googleMapsUrl: i.string().optional(),
      googleMatchConfidence: i.number().optional(),
      googleMatchReason: i.string().optional(),
      googleOpenNow: i.boolean().optional(),
      googlePhone: i.string().optional(),
      googlePhotoName: i.string().optional(),
      googlePhotoUri: i.string().optional(),
      googlePlaceId: i.string().optional(),
      googleRating: i.number().optional(),
      googleReviewCount: i.number().optional(),
      googleWebsite: i.string().optional(),
      googleWeekdayText: i.json().optional(),
      headAccessClass: i.string().optional(),
      headFeeLikely: i.boolean().optional(),
      headFeeReason: i.string().optional(),
      headHoursText: i.json().optional(),
      headLandManager: i.json().optional(),
      headOpenNow: i.boolean().optional(),
      isPrimary: i.boolean().optional(),
      lat: i.number().optional(),
      lon: i.number().optional(),
      name: i.string(),
      parking: i.json().optional(),
      raw: i.json().optional(),
      systemRef: i.string().optional(),
      trailSlug: i.string(),
    }),
    trails: i.entity({
      city: i.string().optional(),
      county: i.string().optional(),
      name: i.string(),
      raw: i.any().optional(),
      state: i.string().optional(),
      summary: i.string().optional(),
      systemRef: i.string(),
      systemSlug: i.string(),
    }),
    trailSegments: i.entity({
      city: i.string().optional(),
      county: i.string().optional(),
      createdBy: i.string().optional(),
      createdDate: i.string().optional(),
      extDataset: i.string(),
      extSegmentRef: i.string(),
      feature: i.string().optional(),
      geometry: i.json().optional(),
      lengthMiles: i.number().optional(),
      modifiedBy: i.string().optional(),
      modifiedDate: i.string().optional(),
      name: i.string().optional(),
      raw: i.json().optional(),
      surface: i.string().optional(),
      systemRef: i.string(),
      systemSlug: i.string(),
      width: i.number().optional(),
    }),
    trailSystems: i.entity({
      amenitiesCounts: i.json().optional(),
      amenitiesIndexScore: i.number().optional(),
      amenityPoints: i.json().optional(),
      asphaltPercent: i.number().optional(),
      bbox: i.json().optional(),
      centroid: i.json().optional(),
      city: i.string().optional(),
      computedAt: i.string().optional(),
      county: i.string().optional(),
      crowdClass: i.string().optional(),
      crowdLastComputedAt: i.number().optional(),
      crowdProxyScore: i.number().optional(),
      crowdReasons: i.json().optional(),
      crowdSignals: i.json().optional(),
      dogsAllowed: i.string().optional(),
      elevationComputedAt: i.string().optional(),
      elevationGainFt: i.number().optional(),
      elevationLossFt: i.number().optional(),
      elevationMaxFt: i.number().optional(),
      elevationMinFt: i.number().optional(),
      elevationProfile: i.json().optional(),
      elevationProvider: i.string().optional(),
      elevationSampleCount: i.number().optional(),
      extDataset: i.string(),
      extSystemRef: i.string(),
      faqs: i.json().optional(),
      gradeP50: i.number().optional(),
      gradeP90: i.number().optional(),
      hazardPoints: i.json().optional(),
      hazards: i.json().optional(),
      hazardsClass: i.string().optional(),
      hazardsLastComputedAt: i.number().optional(),
      hazardsReasons: i.json().optional(),
      hazardsScore: i.number().optional(),
      heatRisk: i.string().optional(),
      highlights: i.json().optional(),
      highlightPoints: i.json().optional(),
      highlightsByType: i.json().optional(),
      highlightsCount: i.number().optional(),
      highlightsLastComputedAt: i.number().optional(),
      leashDetails: i.string().optional(),
      leashPolicy: i.string().optional(),
      lengthMilesTotal: i.number().optional(),
      litKnownSamples: i.number().optional(),
      litPercentKnown: i.number().optional(),
      litYesSamples: i.number().optional(),
      logisticsLastComputedAt: i.number().optional(),
      mudLastComputedAt: i.number().optional(),
      mudRisk: i.string().optional(),
      mudRiskReason: i.string().optional(),
      mudRiskScore: i.number().optional(),
      name: i.string(),
      naturalSurfacePercent: i.number().optional(),
      nightClass: i.string().optional(),
      nightFriendly: i.boolean().optional(),
      nightLastComputedAt: i.number().optional(),
      nightReasons: i.json().optional(),
      nightScore: i.number().optional(),
      nightWinterSignals: i.json().optional(),
      parkingCapacityEstimate: i.number().optional(),
      parkingCount: i.number().optional(),
      parkingFeeKnown: i.boolean().optional(),
      personalization: i.json().optional(),
      personalizationLastComputedAt: i.number().optional(),
      pavedPercentProxy: i.number().optional(),
      policyConfidence: i.number().optional(),
      policyMethod: i.string().optional(),
      policyNotes: i.string().optional(),
      policySourceTitle: i.string().optional(),
      policySourceUrl: i.string().optional(),
      policyVerifiedAt: i.string().optional(),
      raw: i.json().optional(),
      reactiveDogFriendly: i.boolean().optional(),
      roughnessRisk: i.string().optional(),
      segmentCount: i.number().optional(),
      shadeClass: i.string().optional(),
      shadeLastComputedAt: i.number().optional(),
      shadeProxyPercent: i.number().optional(),
      shadeProxyScore: i.number().optional(),
      shadeSources: i.json().optional(),
      shadeProfile: i.json().optional(),
      surfaceProfile: i.json().optional(),
      safety: i.json().optional(),
      safetyLastComputedAt: i.number().optional(),
      accessPoints: i.json().optional(),
      accessRules: i.json().optional(),
      accessRulesClass: i.string().optional(),
      accessRulesLastComputedAt: i.number().optional(),
      accessRulesReasons: i.json().optional(),
      accessRulesScore: i.number().optional(),
      bailoutClass: i.string().optional(),
      bailoutPoints: i.json().optional(),
      bailoutReasons: i.json().optional(),
      bailoutScore: i.number().optional(),
      loopStats: i.json().optional(),
      routeGraphStats: i.json().optional(),
      routeType: i.string().optional(),
      slug: i.string(),
      state: i.string().optional(),
      structureLastComputedAt: i.number().optional(),
      streetLampCountNearTrail: i.number().optional(),
      surfaceBreakdown: i.json().optional(),
      surfaceLastComputedAt: i.number().optional(),
      surfaceSummary: i.json().optional(),
      swimAccessPoints: i.json().optional(),
      swimAccessPointsByType: i.json().optional(),
      swimAccessPointsCount: i.number().optional(),
      swimLikely: i.boolean().optional(),
      trailheadPOIs: i.json().optional(),
      waterLastComputedAt: i.number().optional(),
      waterNearPercent: i.number().optional(),
      waterProfile: i.json().optional(),
      waterNearScore: i.number().optional(),
      waterTypesNearby: i.json().optional(),
      widthSummary: i.json().optional(),
      winterClass: i.string().optional(),
      winterLastComputedAt: i.number().optional(),
      winterLikelyMaintained: i.boolean().optional(),
      winterReasons: i.json().optional(),
      winterScore: i.number().optional(),
      winterTagFound: i.string().optional(),
      primaryTrailHeadId: i.string().optional(),
      seoContent: i.json().optional(),
      trailHeadsLastLinkedAt: i.string().optional(),
      trailHeadsLinkConfidence: i.number().optional(),
      trailHeadsLinkReason: i.string().optional(),
    }),
  },
  links: {
    $streams$files: {
      forward: {
        on: "$streams",
        has: "many",
        label: "$files",
      },
      reverse: {
        on: "$files",
        has: "one",
        label: "$stream",
        onDelete: "cascade",
      },
    },
    $usersLinkedPrimaryUser: {
      forward: {
        on: "$users",
        has: "one",
        label: "linkedPrimaryUser",
        onDelete: "cascade",
      },
      reverse: {
        on: "$users",
        has: "many",
        label: "linkedGuestUsers",
      },
    },
    trailHeadsSystem: {
      forward: {
        on: "trailHeads",
        has: "one",
        label: "system",
      },
      reverse: {
        on: "trailSystems",
        has: "many",
        label: "trailHeads",
      },
    },
    trailSegmentsSystem: {
      forward: {
        on: "trailSegments",
        has: "one",
        label: "system",
      },
      reverse: {
        on: "trailSystems",
        has: "many",
        label: "segments",
      },
    },
  },
  rooms: {},
});

// This helps TypeScript display nicer intellisense
type _AppSchema = typeof _schema;
interface AppSchema extends _AppSchema {}
const schema: AppSchema = _schema;

export type { AppSchema };
export default schema;
